name: pkg
on:
  push:
    tags:
      - v*.*.*
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: 16
          always-auth: true
      - run: yarn cache clean
      - run: yarn install --network-concurrency 1
      - run: echo "//registry.npmjs.org/:_authToken=${NODE_AUTH_TOKEN}" > ~/.npmrc
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
      - run: yarn publish --access=public --non-interactive
